[package]
name = "redis-async"
version = "0.1.2"
authors = ["Ben Ashford <benashford@users.noreply.github.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "An asynchronous futures based Redis client for Rust using Tokio"
repository = "https://github.com/benashford/redis-async-rs"
keywords = ["redis", "tokio"]

[features]
default = []
commands = []

[dependencies]
bytes = "0.4.5"
futures = "0.1.18"
log = "0.4.1"
lwactors = "0.0.4"
tokio = "0.1.0"
tokio-io = "0.1.5"

[dev-dependencies]
futures-cpupool = "0.1.8"